### ISSUE TITLE
Method chat.with_name dont work when we are offline?

### ISSUE THREAD

**Issue by MrSaooty** [alecgorge/jsonapi#422]
Method chat.with_name dont work when we are offline?

With PHP

**Comment by MrSaooty** [comment]
With `JSONAPI-5.6.0-mc1.7.9-R0.2-SNAPSHOT.jar`

**Comment by alecgorge** [comment]
The latest builds should solve this issue.

New builds on Jenkins should be compatible with Spigot 1.8 only: https://ci.alecgorge.com/job/JSONAPI/

It probably isn't perfect, but it is a lot better than it was before.

**Comment by blackarcanis** [comment]
Hi, first thanks a lot for this tool !
Have the same issue here, this is the error returned : 

Array ( [message] => Caught exception: java.lang.reflect.InvocationTargetException at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:606) at com.alecgorge.minecraft.jsonapi.dynamic.Call.call(Call.java:170) at com.alecgorge.minecraft.jsonapi.dynamic.Caller$1.call(Caller.java:94) at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftFuture.run(CraftFuture.java:89) at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:726) at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367) at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657) at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560) at java.lang.Thread.run(Thread.java:745) Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_8_R1/util/Waitable at com.alecgorge.minecraft.jsonapi.dynamic.APIWrapperMethods.getRealisticChatProvider(APIWrapperMethods.java:469) at com.alecgorge.minecraft.jsonapi.dynamic.APIWrapperMethods.chatWithName(APIWrapperMethods.java:501) ... 13 more Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_8_R1.util.Waitable at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) at java.lang.ClassLoader.loadClass(ClassLoader.java:425) at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ... 15 more [code] => 5 ) [source] => chat.with_name )

And we use your last version here => https://ci.alecgorge.com/job/JSONAPI/125/

Is it corrected or not sure ? Thanks a lot for your help !
