### ISSUE TITLE
Still maintained/active?

### ISSUE THREAD

**Issue by tuxillator** [alecgorge/jsonapi#425]
I see a lot of open issues without activity (many of which could be closed) and no commits since Sept 14, 2014. Is this project still active?

**Comment by krisdb2009** [comment]
Sadly I think its dead. IMO

**Comment by lifehome** [comment]
Sorry, didn't get this or you didn't aware that a 1.8 pre-release has been
released?

krisdb2009 <notifications@github.com> 於 2015年2月4日星期三 寫道：

> Sadly I think its dead. IMO
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alecgorge/jsonapi/issues/425#issuecomment-72782836>.
>


-- 
Should you require further information, please do not hesitate to contact
the undersigned.
Thank you very much

Yours sincerely,
Ivan Ip<m@lifeho.me>
Phone: (852) 9806-3212

**Comment by electronicboy** [comment]
Try switching to the 1.8 branch, last commit was a month ago...
There is a working 1.8 build, can't say it's 100% working; more a slow rolling build, you have to remember developers usually have months of working with unstable bukkit builds before it turns stable enough for people to actually start switching over, this update was a lot different in that it just popped out 'stable' one day with no release builds, so normal time constraints of life still exist into such a shorter time period.

**Comment by alecgorge** [comment]
It is alive but I'm not sure it is active for now.

I don't play Minecraft anymore and I haven't for years. With the implosion of CraftBukkit, I have absolutely no idea what API to write this plugin against because I can't figure out what people are actually using. Is it Spigot? Is it Sponge? Is it Forge?

I want to write JSONAPI v6 that supports this full platform natively and remove pretty much all of the legacy support for the old API, old authentication strategies and old platform support but I don't feel comfortable putting in the substantial effort necessary to keep up with things because it feels like any of them can disappear at any time.

I would also be open to adding any number contributors and pull requests are always accepted :)

**Comment by digitalcrowd** [comment]
I would got with Spigot for 1.8. That is the "new" Bukkit.

**Comment by MetalCar** [comment]
That sounds cool. We are using Spigot and are glad when the new version come out.

**Comment by alecgorge** [comment]
New builds on Jenkins should be compatible with Spigot 1.8 only: https://ci.alecgorge.com/job/JSONAPI/

It probably isn't perfect, but it is a lot better than it was before.

**Comment by alecgorge** [comment]
Please see #426 if you would like to discuss new features and open an issue for new bugs
