### ISSUE TITLE
Socket sending half JSON

### ISSUE THREAD

**Issue by bryns1** [alecgorge/jsonapi#507]
When subscribed to stream sources the JSONAPI is sending objects over multiple socket messages (packages?). This leads to JSON.parse freaking out and throwing errors. 

```javascript
this._socket.on("data", val => {
      let arr = val.toString().trim().split("\r\n");
      // log entry...

      arr.forEach((json, i) => {
          // log i/arr.length

          try{
              let data = JSON.parse(json);
          }catch(err){
              // log error
          }
      })
})
```

![screen shot 2017-09-11 at 6 46 23 pm](https://user-images.githubusercontent.com/15933846/30266068-957654d0-9721-11e7-976c-8cb74cfeaed0.png)

**Comment by koesie10** [comment]
This is expected because it is a normal TCP socket. You will need to gather all received messages in a buffer and look for `\r\n`. That is how you know a complete message has been received. Multiple messages can also come concatenated in one TCP packet, so you will also need to expect that.

If you don't want to handle all this yourself, it's probably easier to connect to the WebSocket, which handles all of this for you using its protocol.
